*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun 15 21:46:36 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 04 June 2020 12:34:29
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: izf8zh4289t5rik0csaz0tz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/fastdfs_client
writing pidfile to uwsgi.pid
detected binary path: /root/anaconda3/envs/flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/fastdfs_client
your processes number limit is 30645
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x13e0320
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "client.py", line 3, in <module>
    from API import *
  File "./API/__init__.py", line 8, in <module>
    from util import Generate_UUID, sendMsg, Md5Content
  File "./util/__init__.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 29355)
spawned uWSGI worker 1 (pid: 29360, cores: 2)
spawned uWSGI worker 2 (pid: 29361, cores: 2)
spawned uWSGI worker 3 (pid: 29363, cores: 2)
spawned uWSGI worker 4 (pid: 29364, cores: 2)
Traceback (most recent call last):
  File "./client.py", line 3, in <module>
    from API import *
  File "./API/__init__.py", line 8, in <module>
    from util import Generate_UUID, sendMsg, Md5Content
  File "./util/__init__.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 29363|app: -1|req: -1/1] 219.132.115.132 () {52 vars in 992 bytes} [Mon Jun 15 21:48:26 2020] POST /fdfsfile/api => generated 21 bytes in 2 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 29360)...
Gracefully killing worker 3 (pid: 29363)...
Gracefully killing worker 2 (pid: 29361)...
Gracefully killing worker 4 (pid: 29364)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/fastdfs_client
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/anaconda3/envs/flask/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun 15 21:49:39 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 04 June 2020 12:34:29
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: izf8zh4289t5rik0csaz0tz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/fastdfs_client
detected binary path: /root/anaconda3/envs/flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/fastdfs_client
your processes number limit is 30645
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x1ce7c50
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "client.py", line 3, in <module>
    from API import *
  File "./API/__init__.py", line 8, in <module>
    from util import Generate_UUID, sendMsg, Md5Content
  File "./util/__init__.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 29355)
spawned uWSGI worker 1 (pid: 29602, cores: 2)
spawned uWSGI worker 2 (pid: 29603, cores: 2)
spawned uWSGI worker 3 (pid: 29605, cores: 2)
spawned uWSGI worker 4 (pid: 29606, cores: 2)
Traceback (most recent call last):
  File "./client.py", line 3, in <module>
    from API import *
  File "./API/__init__.py", line 8, in <module>
    from util import Generate_UUID, sendMsg, Md5Content
  File "./util/__init__.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 29605|app: -1|req: -1/1] 219.132.115.132 () {52 vars in 992 bytes} [Mon Jun 15 21:50:49 2020] POST /fdfsfile/api => generated 21 bytes in 2 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
...gracefully killing workers...
Gracefully killing worker 2 (pid: 29603)...
Gracefully killing worker 4 (pid: 29606)...
Gracefully killing worker 1 (pid: 29602)...
Gracefully killing worker 3 (pid: 29605)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/fastdfs_client
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/anaconda3/envs/flask/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun 15 21:52:46 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 04 June 2020 12:34:29
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: izf8zh4289t5rik0csaz0tz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/fastdfs_client
detected binary path: /root/anaconda3/envs/flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/fastdfs_client
your processes number limit is 30645
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x1e36c50
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1e36c50 pid: 29355 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 29355)
spawned uWSGI worker 1 (pid: 29832, cores: 2)
spawned uWSGI worker 2 (pid: 29833, cores: 2)
spawned uWSGI worker 3 (pid: 29835, cores: 2)
spawned uWSGI worker 4 (pid: 29836, cores: 2)
[pid: 29836|app: 0|req: 1/1] 219.132.115.132 () {52 vars in 992 bytes} [Mon Jun 15 21:54:02 2020] POST /fdfsfile/api => generated 232 bytes in 1 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
[pid: 29836|app: 0|req: 2/2] 219.132.115.132 () {52 vars in 992 bytes} [Mon Jun 15 21:56:11 2020] POST /fdfsfile/api => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 1)
...gracefully killing workers...
Gracefully killing worker 2 (pid: 29833)...
Gracefully killing worker 4 (pid: 29836)...
Gracefully killing worker 1 (pid: 29832)...
Gracefully killing worker 3 (pid: 29835)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/fastdfs_client
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/anaconda3/envs/flask/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun 15 21:58:52 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 04 June 2020 12:34:29
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: izf8zh4289t5rik0csaz0tz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/fastdfs_client
detected binary path: /root/anaconda3/envs/flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/fastdfs_client
your processes number limit is 30645
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x1de3c50
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1de3c50 pid: 29355 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 29355)
spawned uWSGI worker 1 (pid: 30160, cores: 2)
spawned uWSGI worker 2 (pid: 30161, cores: 2)
spawned uWSGI worker 3 (pid: 30163, cores: 2)
spawned uWSGI worker 4 (pid: 30164, cores: 2)
[2020-06-15 21:59:14,511] ERROR in app: Exception on /fdfsfile/api [POST]
Traceback (most recent call last):
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "./API/__init__.py", line 29, in post
    ext_name = os.path.splitext(file.filename)[-1][1:]
AttributeError: 'NoneType' object has no attribute 'filename'
[pid: 30164|app: 0|req: 1/1] 219.132.115.132 () {52 vars in 984 bytes} [Mon Jun 15 21:59:14 2020] POST /fdfsfile/api => generated 37 bytes in 5 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
[2020-06-15 21:59:47,503] ERROR in app: Exception on /fdfsfile/api [POST]
Traceback (most recent call last):
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "./API/__init__.py", line 35, in post
    UUID = Generate_UUID(ret)
  File "./util/__init__.py", line 17, in Generate_UUID
    m.update(restcontent)
TypeError: Unicode-objects must be encoded before hashing
[pid: 30161|app: 0|req: 1/2] 219.132.115.132 () {52 vars in 992 bytes} [Mon Jun 15 21:59:44 2020] POST /fdfsfile/api => generated 37 bytes in 2790 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 30160)...
Gracefully killing worker 2 (pid: 30161)...
Gracefully killing worker 3 (pid: 30163)...
Gracefully killing worker 4 (pid: 30164)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/fastdfs_client
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/anaconda3/envs/flask/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun 15 22:03:34 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 04 June 2020 12:34:29
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: izf8zh4289t5rik0csaz0tz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/fastdfs_client
detected binary path: /root/anaconda3/envs/flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/fastdfs_client
your processes number limit is 30645
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x24d5c50
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x24d5c50 pid: 29355 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 29355)
spawned uWSGI worker 1 (pid: 30437, cores: 2)
spawned uWSGI worker 2 (pid: 30438, cores: 2)
spawned uWSGI worker 3 (pid: 30440, cores: 2)
spawned uWSGI worker 4 (pid: 30441, cores: 2)
[2020-06-15 22:04:24,337] ERROR in app: Exception on /fdfsfile/api [POST]
Traceback (most recent call last):
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "./API/__init__.py", line 35, in post
    UUID = Generate_UUID(ret.encode("utf-8"))
AttributeError: 'dict' object has no attribute 'encode'
[pid: 30440|app: 0|req: 1/1] 219.132.115.132 () {52 vars in 992 bytes} [Mon Jun 15 22:04:21 2020] POST /fdfsfile/api => generated 37 bytes in 2763 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 30437)...
Gracefully killing worker 2 (pid: 30438)...
Gracefully killing worker 4 (pid: 30441)...
Gracefully killing worker 3 (pid: 30440)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/fastdfs_client
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/anaconda3/envs/flask/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun 15 22:08:21 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 04 June 2020 12:34:29
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: izf8zh4289t5rik0csaz0tz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/fastdfs_client
detected binary path: /root/anaconda3/envs/flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/fastdfs_client
your processes number limit is 30645
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x20ffc50
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x20ffc50 pid: 29355 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 29355)
spawned uWSGI worker 1 (pid: 30695, cores: 2)
spawned uWSGI worker 2 (pid: 30696, cores: 2)
spawned uWSGI worker 3 (pid: 30698, cores: 2)
spawned uWSGI worker 4 (pid: 30699, cores: 2)
[2020-06-15 22:08:58,284] ERROR in app: Exception on /fdfsfile/api [POST]
Traceback (most recent call last):
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "./API/__init__.py", line 35, in post
    UUID = Generate_UUID(temp)
  File "./util/__init__.py", line 15, in Generate_UUID
    restcontent = json.dumps(Ret)
  File "/root/anaconda3/envs/flask/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/root/anaconda3/envs/flask/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/root/anaconda3/envs/flask/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/anaconda3/envs/flask/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
[pid: 30698|app: 0|req: 1/1] 219.132.115.132 () {52 vars in 992 bytes} [Mon Jun 15 22:08:55 2020] POST /fdfsfile/api => generated 37 bytes in 2759 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 30695)...
Gracefully killing worker 2 (pid: 30696)...
Gracefully killing worker 4 (pid: 30699)...
Gracefully killing worker 3 (pid: 30698)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/fastdfs_client
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/anaconda3/envs/flask/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun 15 22:15:51 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 04 June 2020 12:34:29
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: izf8zh4289t5rik0csaz0tz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/fastdfs_client
detected binary path: /root/anaconda3/envs/flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/fastdfs_client
your processes number limit is 30645
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
Python main interpreter initialized at 0xb62c50
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xb62c50 pid: 29355 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 29355)
spawned uWSGI worker 1 (pid: 31094, cores: 2)
spawned uWSGI worker 2 (pid: 31095, cores: 2)
spawned uWSGI worker 3 (pid: 31097, cores: 2)
spawned uWSGI worker 4 (pid: 31098, cores: 2)
[2020-06-15 22:16:36,566] ERROR in app: Exception on /fdfsfile/api [POST]
Traceback (most recent call last):
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "./API/__init__.py", line 35, in post
    UUID = Generate_UUID(ret)
  File "./util/__init__.py", line 15, in Generate_UUID
    restcontent = json.dumps(Ret,encoding="UTF-8", ensure_ascii=False)
  File "/root/anaconda3/envs/flask/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'encoding'
[pid: 31097|app: 0|req: 1/1] 219.132.115.132 () {52 vars in 992 bytes} [Mon Jun 15 22:16:33 2020] POST /fdfsfile/api => generated 37 bytes in 2772 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 2 (pid: 31095)...
Gracefully killing worker 4 (pid: 31098)...
Gracefully killing worker 1 (pid: 31094)...
Gracefully killing worker 3 (pid: 31097)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/fastdfs_client
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/anaconda3/envs/flask/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun 15 22:19:20 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 04 June 2020 12:34:29
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: izf8zh4289t5rik0csaz0tz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/fastdfs_client
detected binary path: /root/anaconda3/envs/flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/fastdfs_client
your processes number limit is 30645
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
Python main interpreter initialized at 0xceac50
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xceac50 pid: 29355 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 29355)
spawned uWSGI worker 1 (pid: 31288, cores: 2)
spawned uWSGI worker 2 (pid: 31289, cores: 2)
spawned uWSGI worker 3 (pid: 31291, cores: 2)
spawned uWSGI worker 4 (pid: 31292, cores: 2)
[2020-06-15 22:21:25,450] ERROR in app: Exception on /fdfsfile/api [POST]
Traceback (most recent call last):
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/anaconda3/envs/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "./API/__init__.py", line 35, in post
    UUID = Generate_UUID(ret)
  File "./util/__init__.py", line 17, in Generate_UUID
    m.update(restcontent)
TypeError: Unicode-objects must be encoded before hashing
[pid: 31289|app: 0|req: 1/1] 219.132.115.132 () {52 vars in 992 bytes} [Mon Jun 15 22:21:22 2020] POST /fdfsfile/api => generated 37 bytes in 3211 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 31288)...
Gracefully killing worker 2 (pid: 31289)...
Gracefully killing worker 3 (pid: 31291)...
Gracefully killing worker 4 (pid: 31292)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/fastdfs_client
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/anaconda3/envs/flask/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun 15 22:23:40 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 04 June 2020 12:34:29
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: izf8zh4289t5rik0csaz0tz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/fastdfs_client
detected binary path: /root/anaconda3/envs/flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/fastdfs_client
your processes number limit is 30645
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x231ec50
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x231ec50 pid: 29355 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 29355)
spawned uWSGI worker 1 (pid: 31537, cores: 2)
spawned uWSGI worker 2 (pid: 31538, cores: 2)
spawned uWSGI worker 3 (pid: 31540, cores: 2)
spawned uWSGI worker 4 (pid: 31541, cores: 2)
[pid: 31538|app: 0|req: 1/1] 219.132.115.132 () {52 vars in 992 bytes} [Mon Jun 15 22:24:12 2020] POST /fdfsfile/api => generated 391 bytes in 3452 msecs (HTTP/1.1 201) 2 headers in 77 bytes (1 switches on core 0)
